name: Sync Agent Documentation

on:
  push:
    paths:
      - 'src/commands/scan-options.ts'
      - 'src/commands/scan.ts'
      - 'src/prebid.ts'
      - 'CLAUDE.md'
      - 'GEMINI.md'
      - 'AGENTS.md'
      - 'scripts/sync-agent-docs.js'
  pull_request:
    paths:
      - 'src/commands/scan-options.ts'
      - 'src/commands/scan.ts'
      - 'src/prebid.ts'
      - 'CLAUDE.md'
      - 'GEMINI.md'
      - 'AGENTS.md'
      - 'scripts/sync-agent-docs.js'

jobs:
  sync-docs:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Validate documentation consistency
        run: npm run validate-docs
        
      - name: Sync agent documentation
        run: npm run sync-agent-docs
        
      - name: Check for changes
        id: verify-changed-files
        run: |
          if git diff --quiet; then
            echo "changed=false" >> $GITHUB_OUTPUT
          else
            echo "changed=true" >> $GITHUB_OUTPUT
          fi
          
      - name: Show changes
        if: steps.verify-changed-files.outputs.changed == 'true'
        run: |
          echo "Documentation changes detected:"
          git diff --name-only
          git diff
          
      - name: Commit changes
        if: steps.verify-changed-files.outputs.changed == 'true' && github.event_name == 'push'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add CLAUDE.md GEMINI.md AGENTS.md
          git commit -m "docs: auto-sync agent documentation" || exit 0
          git push
          
      - name: Comment on PR
        if: steps.verify-changed-files.outputs.changed == 'true' && github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '🤖 **Agent Documentation Sync**\n\nThe agent documentation files need to be updated to stay in sync. Please run `npm run sync-agent-docs` locally and commit the changes.'
            })
            
      - name: Fail if docs out of sync on PR
        if: steps.verify-changed-files.outputs.changed == 'true' && github.event_name == 'pull_request'
        run: |
          echo "❌ Agent documentation is out of sync!"
          echo "Please run 'npm run sync-agent-docs' locally and commit the changes."
          exit 1